# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
#Importar numpy
import numpy as np

In [2]:
#Ejercicio1

In [2]:
np.zeros(12)
tiempo=np.zeros(12)
print(tiempo)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [162]:
#ejercicio2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

In [6]:
Puntos = np.zeros(10)      
Puntos[4] = 10           
print(Puntos)          

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [ ]:
#ejercicio3

In [7]:
arr = np.arange(10, 50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
#ejercicio4

In [8]:
arr = np.arange(0, 9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#ejercicio5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

In [9]:
np.random.rand(100)
my_array = np.random.rand(100)
media = my_array.mean()
var= my_array.var()

print("Media:", media)
print("varianza:",var)

Media: 0.5232696827512509
varianza: 0.08711286321794283


In [ ]:
#ejercicio6: Calcular la media de un arreglo usando np.sum

In [11]:
my_array = np.random.rand(100)
suma = np.sum(my_array) 
media = suma / len(my_array)  

print("Media:", media)

Media: 0.5401180856503263


In [138]:
#ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean

In [16]:
my_array = np.random.rand(50)
media= my_array.mean()
diferencias_al_cuadrado = (my_array - media) ** 2
suma_total = np.sum(diferencias_al_cuadrado)
varianza = suma_total / len(my_array)
print("Varianza",varianza)

Varianza 0.08134112760345281


In [20]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn.

In [23]:
total = np.random.randn(10, 3)
print(total)

[[-0.48946329 -0.20581847 -0.65920731]
 [-1.26639588  0.92648908 -0.27934055]
 [ 1.36981384 -1.41983829  0.52998086]
 [-1.33721184  1.15927162  0.85471039]
 [ 1.02485942 -0.90577355  1.28076039]
 [-0.13430435  0.54745327  1.41310417]
 [ 1.49937265  0.6697454   0.81308827]
 [ 0.43461687 -0.53228217  1.89359031]
 [-0.59711189 -0.66746913 -0.5237105 ]
 [ 0.37570264 -0.68826274 -0.09359157]]
